In [134]:
from random import Random
from numpy import *
from time import *
from datetime import *
from IPython.display import display
import math
import scipy as sp

import matplotlib.pyplot as plt
from sklearn import gaussian_process
from sklearn.gaussian_process.kernels import Matern, WhiteKernel, ConstantKernel, RBF

%matplotlib inline
%load_ext autoreload
%autoreload 2

import scipy.stats as st
import numpy as np
import math

def bsformula(cp, s, k, rf, t, v, div):
        """ Price an option using the Black-Scholes model.
        cp: +1/-1 for call/put
        s: initial stock price
        k: strike price
        t: expiration time
        v: volatility
        rf: risk-free rate
        div: dividend
        """

        d1 = (np.log(s/k)+(rf-div+0.5*v*v)*t)/(v*np.sqrt(t))
        d2 = d1 - v*np.sqrt(t)

        optprice = (cp*s*np.exp(-div*t)*st.norm.cdf(cp*d1)) - (cp*k*np.exp(-rf*t)*st.norm.cdf(cp*d2))
        delta = cp*st.norm.cdf(cp*d1)
        vega  = s*np.sqrt(t)*st.norm.pdf(d1)
        return optprice, delta, vega
    
KC = 130
KP = 70
r = 0.002
sigma = 0.4
T = 2.0
S0 = 100

lb = 0
ub = 300
training_number = 3
testing_number = 100

call = lambda x,y: bsformula(1, lb+(ub-lb)*x, KC, r, T, y, 0)[0]
put = lambda x,y: bsformula(-1, lb+(ub-lb)*x, KP, r, T, y, 0)[0]

x_train = np.array(np.linspace(0.01,1.0, training_number), dtype='float32').reshape(training_number, 1)
x_test = np.array(np.linspace(0.01,1.0, testing_number), dtype='float32').reshape(testing_number, 1)

y_train = []
    
for idx in range(len(x_train)):
    y_train.append(call(x_train[idx], sigma))
y_train = np.array(y_train)

sk_kernel = RBF(length_scale=1.0, length_scale_bounds=(0.01, 10000.0)) #+ WhiteKernel(noise_level = 1e-12) #100000.0
gp = gaussian_process.GaussianProcessRegressor(kernel=sk_kernel, n_restarts_optimizer=20)
gp.fit(x_train,y_train)
y_pred, sigma_hat = gp.predict(x_test, return_std=True)
    
l = gp.kernel_.length_scale
rbf= gaussian_process.kernels.RBF(length_scale=l)
 
Kernel= rbf(x_train, x_train)
K_y = Kernel + np.eye(training_number) * 1e-8
L, lower = sp.linalg.cho_factor(K_y, lower=True)
L1 = sp.linalg.cholesky(K_y, lower=True)


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [111]:
A1 = L@L.T
display(A1)
display(np.linalg.norm(A1))
B = A1 - K_y
display(np.linalg.norm(B)/np.linalg.norm(A1)) 
#relative error of "Cho_factor" algorithm
#This algorithm is problematic??????? For 3x3 matrix there should be very small error because of the simplicity???

array([[1.06293699, 0.49465567, 0.07252614],
       [0.49465567, 1.06292135, 0.49318154],
       [0.07252614, 0.49318154, 1.00000001]])

2.0605779473442127

0.2444257296083435

In [112]:
A2 = L1@L1.T
display(A2)
display(np.linalg.norm(A2))
B = A2 - K_y
display(np.linalg.norm(B)/np.linalg.norm(A2)) 
#relative error of "Cholesky" algorithm

array([[1.00000001, 0.2508412 , 0.00395909],
       [0.2508412 , 1.00000001, 0.25084126],
       [0.00395909, 0.25084126, 1.00000001]])

1.8032517027984196

1.30605099907616e-16

In [132]:
K = array([[1,2,3],[2,5,6],[3,6,11]]) #Lets use some simple number in a 3x3 matrix for testing
display(K)

array([[ 1,  2,  3],
       [ 2,  5,  6],
       [ 3,  6, 11]])

In [140]:
L = sp.linalg.cholesky(K, lower=True)
display(L)
display(L@L.T)

array([[1.        , 0.        , 0.        ],
       [2.        , 1.        , 0.        ],
       [3.        , 0.        , 1.41421356]])

array([[ 1.,  2.,  3.],
       [ 2.,  5.,  6.],
       [ 3.,  6., 11.]])

In [142]:
L, lower = sp.linalg.cho_factor(K, lower=True)
display(L)
display(L@L.T)

array([[1.        , 2.        , 3.        ],
       [2.        , 1.        , 6.        ],
       [3.        , 0.        , 1.41421356]])

array([[14.        , 22.        ,  7.24264069],
       [22.        , 41.        , 14.48528137],
       [ 7.24264069, 14.48528137, 11.        ]])